<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\MiParte.Contracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Auth\MiParte.Auth.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.54.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
