<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\MiParte.Contracts.csproj" />
    <ProjectReference Include="..\Core.Domain\MiParte.Core.Domain.csproj" />
    <ProjectReference Include="..\Core.Infrastructure\MiParte.Core.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
